# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f82d261da78bc936f4c88a1d4a78c66e3943ccd8995c1cb43130f349f1b6e08034a2a318b8a7fa5474da0bd10f2317df62d992d681d8a201ba0ef94ee2f605

test:
  secret_key_base: a854a8d4de2d3b436c066ef6fa0cee6c17b680c731827397d0a42a9308c15f033dab41efc7d65bb88f60677ef360eb2ecac22ec13a16e7160c44841f0131b8f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
